server:
  port: 0 #random port 랜덤포트 사용

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/msa_user_service
    username: msa_test
    password: msatest

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the simple E-commerce.

logging:
  level:
    com.example.userservice: debug

token:
  expiration_time: 86400000 # a day
  secret: custom_user_token