server:
  port: 0 #random port 랜덤포트 사용

spring:
  application:
    name: user-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


  cloud:
    config:
      name: ecommerce

  config:
    import: optional:configserver:http://localhost:8888 # config server client 설정

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/msa_user_service
    username: msa_test
    password: msatest

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the simple E-commerce.

logging:
  level:
    com.example.userservice: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

#token:
#  expiration_time: 86400000 # a day
#  secret: custom_user_token