server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
#          uri: file:///Users/joshua/Desktop/Study/git-local-repo # file protocol ???? ???
          uri: https://github.com/mingj7235/spring-cloud-config.git
          default-label: main
#          username: # private repository ? ??
#          password:
