server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  # local native file ? ?? ? ??
#  profiles:
#    active: native

  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/Desktop/Study/native-file-repo
        git:
#          uri: file:///Users/joshua/Desktop/Study/git-local-repo # file protocol ???? ???
          uri: https://github.com/mingj7235/spring-cloud-config.git
          default-label: main
#          username: # private repository ? ??
#          password:
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

encrypt:
  #key: abcdefghijklmnopqrstuvexyz1234567890
  key-store:
    location: file://${user.home}/Desktop/Study/keystore/apiEncryptionKey.jks
    password: 1q2w3e4r
    alias: apiEncryptionKey

